spring:
  application:
    name: ioomex-admin-springboot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx:xx/xx?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: xx
    password: xx
  session:
    timeout: 86400 
server:
  port: 9081
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isdelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    map-underscore-to-camel-case: false